// Users data with realistic participant information
export const usersData = [
  // Admin user
  {
    firstName: 'Admin',
    paternalLastName: 'ConfeJAS',
    maternalLastName: 'System',
    dni: '00000001',
    email: 'admin@confejas.com',
    password: 'password',
    stakeName: 'Los Olivos',
    ward: 'Administración',
    age: '30',
    isMemberOfTheChurch: true,
    roleName: 'Admin',
  },
  // Staff users (5 generic)
  {
    firstName: 'Staff',
    paternalLastName: 'One',
    maternalLastName: 'ConfeJAS',
    dni: '00000002',
    email: 'staff1@confejas.com',
    password: 'password',
    stakeName: 'Los Olivos',
    ward: 'Staff',
    age: '25',
    isMemberOfTheChurch: true,
    roleName: 'Staff',
  },
  {
    firstName: 'Staff',
    paternalLastName: 'Two',
    maternalLastName: 'ConfeJAS',
    dni: '00000003',
    email: 'staff2@confejas.com',
    password: 'password',
    stakeName: 'Los Olivos',
    ward: 'Staff',
    age: '26',
    isMemberOfTheChurch: true,
    roleName: 'Staff',
  },
  {
    firstName: 'Staff',
    paternalLastName: 'Three',
    maternalLastName: 'ConfeJAS',
    dni: '00000004',
    email: 'staff3@confejas.com',
    password: 'password',
    stakeName: 'Los Olivos',
    ward: 'Staff',
    age: '27',
    isMemberOfTheChurch: true,
    roleName: 'Staff',
  },
  {
    firstName: 'Staff',
    paternalLastName: 'Four',
    maternalLastName: 'ConfeJAS',
    dni: '00000005',
    email: 'staff4@confejas.com',
    password: 'password',
    stakeName: 'Los Olivos',
    ward: 'Staff',
    age: '28',
    isMemberOfTheChurch: true,
    roleName: 'Staff',
  },
  {
    firstName: 'Staff',
    paternalLastName: 'Five',
    maternalLastName: 'ConfeJAS',
    dni: '00000006',
    email: 'staff5@confejas.com',
    password: 'password',
    stakeName: 'Los Olivos',
    ward: 'Staff',
    age: '29',
    isMemberOfTheChurch: true,
    roleName: 'Staff',
  },
];

/* OLD SEED DATA - COMMENTED OUT FOR REFERENCE
export const usersDataOld = [
  // Staff members
  {
    firstName: 'Celeste Mariyen',
    paternalLastName: 'Aguinaga',
    maternalLastName: 'Aguayo',
    dni: '72767381',
    birthDate: new Date('1999-10-07'),
    gender: 'Female',
    phone: '980873771',
    email: 'cmariyenaguinaga@gmail.com',
    address: 'Mz I lote 33 urb. San Diego',
    region: 'Lima',
    department: 'Lima',
    hasArrived: true,
    medicalCondition: null,
    keyCode: null,
    roleName: 'Staff',
  },
  {
    firstName: 'Carlos Alberto',
    paternalLastName: 'Rodriguez',
    maternalLastName: 'Martinez',
    dni: '45678912',
    birthDate: new Date('1985-03-15'),
    gender: 'Male',
    phone: '987654321',
    email: 'carlos.rodriguez@email.com',
    address: 'Av. Principal 123',
    region: 'Lima',
    department: 'Lima',
    hasArrived: true,
    medicalCondition: null,
    keyCode: 'KEY001',
    roleName: 'Staff',
  },
  {
    firstName: 'Ana Maria',
    paternalLastName: 'Garcia',
    maternalLastName: 'Lopez',
    dni: '12345678',
    birthDate: new Date('1992-07-22'),
    gender: 'Female',
    phone: '912345678',
    email: 'ana.garcia@email.com',
    address: 'Jr. Los Olivos 456',
    region: 'Arequipa',
    department: 'Arequipa',
    hasArrived: false,
    medicalCondition: 'Diabetes tipo 2',
    keyCode: 'KEY002',
    roleName: 'Staff',
  },

  // Admin users
  {
    firstName: 'Juan Carlos',
    paternalLastName: 'Mendoza',
    maternalLastName: 'Silva',
    dni: '87654321',
    birthDate: new Date('1980-12-10'),
    gender: 'Male',
    phone: '998877665',
    email: 'admin@confejas.com',
    address: 'Av. Administración 789',
    region: 'Lima',
    department: 'Lima',
    hasArrived: true,
    medicalCondition: null,
    keyCode: 'ADMIN001',
    roleName: 'Admin',
  },

  // Counselors
  {
    firstName: 'Patricia Elena',
    paternalLastName: 'Vargas',
    maternalLastName: 'Castillo',
    dni: '56789123',
    birthDate: new Date('1988-05-18'),
    gender: 'Female',
    phone: '955443322',
    email: 'patricia.vargas@email.com',
    address: 'Calle Counseling 321',
    region: 'Cusco',
    department: 'Cusco',
    hasArrived: true,
    medicalCondition: null,
    keyCode: 'COUN001',
    roleName: 'Counselor',
  },
  {
    firstName: 'Miguel Angel',
    paternalLastName: 'Torres',
    maternalLastName: 'Ruiz',
    dni: '34567891',
    birthDate: new Date('1983-09-25'),
    gender: 'Male',
    phone: '944556677',
    email: 'miguel.torres@email.com',
    address: 'Psje. La Esperanza 654',
    region: 'Trujillo',
    department: 'La Libertad',
    hasArrived: true,
    medicalCondition: null,
    keyCode: 'COUN002',
    roleName: 'Counselor',
  },

  // Participants
  {
    firstName: 'Sofia Isabella',
    paternalLastName: 'Ramirez',
    maternalLastName: 'Flores',
    dni: '78912345',
    birthDate: new Date('2001-04-12'),
    gender: 'Female',
    phone: '933221100',
    email: 'sofia.ramirez@email.com',
    address: 'Urb. Los Pinos 987',
    region: 'Piura',
    department: 'Piura',
    hasArrived: true,
    medicalCondition: null,
    keyCode: null,
    roleName: 'Participant',
  },
  {
    firstName: 'Diego Alejandro',
    paternalLastName: 'Morales',
    maternalLastName: 'Herrera',
    dni: '23456789',
    birthDate: new Date('2000-11-08'),
    gender: 'Male',
    phone: '922334455',
    email: 'diego.morales@email.com',
    address: 'Av. Juventud 147',
    region: 'Iquitos',
    department: 'Loreto',
    hasArrived: false,
    medicalCondition: 'Asma leve',
    keyCode: null,
    roleName: 'Participant',
  },
  {
    firstName: 'Valentina Nicole',
    paternalLastName: 'Castro',
    maternalLastName: 'Valdez',
    dni: '91234567',
    birthDate: new Date('1998-08-30'),
    gender: 'Female',
    phone: '911223344',
    email: 'valentina.castro@email.com',
    address: 'Jr. Las Flores 258',
    region: 'Huancayo',
    department: 'Junin',
    hasArrived: true,
    medicalCondition: null,
    keyCode: null,
    roleName: 'Participant',
  },
  {
    firstName: 'Sebastian Eduardo',
    paternalLastName: 'Jimenez',
    maternalLastName: 'Peña',
    dni: '67891234',
    birthDate: new Date('1999-02-14'),
    gender: 'Male',
    phone: '955667788',
    email: 'sebastian.jimenez@email.com',
    address: 'Calle San Martin 369',
    region: 'Chiclayo',
    department: 'Lambayeque',
    hasArrived: true,
    medicalCondition: null,
    keyCode: null,
    roleName: 'Participant',
  },
  {
    firstName: 'Camila Andrea',
    paternalLastName: 'Ramos',
    maternalLastName: 'Gonzalez',
    dni: '45612378',
    birthDate: new Date('2002-06-03'),
    gender: 'Female',
    phone: '944558899',
    email: 'camila.ramos@email.com',
    address: 'Av. Los Heroes 741',
    region: 'Tacna',
    department: 'Tacna',
    hasArrived: false,
    medicalCondition: 'Alergia a mariscos',
    keyCode: null,
    roleName: 'Participant',
  },
  {
    firstName: 'Mateo Ignacio',
    paternalLastName: 'Sandoval',
    maternalLastName: 'Medina',
    dni: '32178945',
    birthDate: new Date('2001-12-21'),
    gender: 'Male',
    phone: '933445566',
    email: 'mateo.sandoval@email.com',
    address: 'Psje. El Dorado 852',
    region: 'Cajamarca',
    department: 'Cajamarca',
    hasArrived: true,
    medicalCondition: null,
    keyCode: null,
    roleName: 'Participant',
  },
  {
    firstName: 'Isabella Fernanda',
    paternalLastName: 'Delgado',
    maternalLastName: 'Rojas',
    dni: '78945612',
    birthDate: new Date('2000-01-17'),
    gender: 'Female',
    phone: '922773355',
    email: 'isabella.delgado@email.com',
    address: 'Urb. Santa Rosa 963',
    region: 'Ayacucho',
    department: 'Ayacucho',
    hasArrived: true,
    medicalCondition: null,
    keyCode: null,
    roleName: 'Participant',
  },
  {
    firstName: 'Nicolas Emilio',
    paternalLastName: 'Vega',
    maternalLastName: 'Paredes',
    dni: '15948726',
    birthDate: new Date('1997-09-05'),
    gender: 'Male',
    phone: '911884477',
    email: 'nicolas.vega@email.com',
    address: 'Jr. La Libertad 159',
    region: 'Pucallpa',
    department: 'Ucayali',
    hasArrived: false,
    medicalCondition: 'Hipertensión',
    keyCode: null,
    roleName: 'Participant',
  },
];
*/
