// Users data with realistic participant information
export const usersData = [
  // Admin user
  {
    firstName: 'Admin',
    paternalLastName: 'ConfeJAS',
    maternalLastName: 'System',
    dni: '00000001',
    email: 'admin@confejas.com',
    password: 'password',
    stakeName: 'Estaca Los Olivos',
    ward: 'Administración',
    age: '30',
    isMemberOfTheChurch: true,
    roleName: 'Admin',
  },
  // Staff users (5 generic)
  {
    firstName: 'Staff',
    paternalLastName: 'One',
    maternalLastName: 'ConfeJAS',
    dni: '00000002',
    email: 'staff1@confejas.com',
    password: 'password',
    stakeName: 'Estaca Los Olivos',
    ward: 'Staff',
    age: '25',
    isMemberOfTheChurch: true,
    roleName: 'Staff',
  },
  {
    firstName: 'Staff',
    paternalLastName: 'Two',
    maternalLastName: 'ConfeJAS',
    dni: '00000003',
    email: 'staff2@confejas.com',
    password: 'password',
    stakeName: 'Estaca Los Olivos',
    ward: 'Staff',
    age: '26',
    isMemberOfTheChurch: true,
    roleName: 'Staff',
  },
  {
    firstName: 'Staff',
    paternalLastName: 'Three',
    maternalLastName: 'ConfeJAS',
    dni: '00000004',
    email: 'staff3@confejas.com',
    password: 'password',
    stakeName: 'Estaca Los Olivos',
    ward: 'Staff',
    age: '27',
    isMemberOfTheChurch: true,
    roleName: 'Staff',
  },
  {
    firstName: 'Staff',
    paternalLastName: 'Four',
    maternalLastName: 'ConfeJAS',
    dni: '00000005',
    email: 'staff4@confejas.com',
    password: 'password',
    stakeName: 'Estaca Los Olivos',
    ward: 'Staff',
    age: '28',
    isMemberOfTheChurch: true,
    roleName: 'Staff',
  },
  {
    firstName: 'Staff',
    paternalLastName: 'Five',
    maternalLastName: 'ConfeJAS',
    dni: '00000006',
    email: 'staff5@confejas.com',
    password: 'password',
    stakeName: 'Estaca Los Olivos',
    ward: 'Staff',
    age: '29',
    isMemberOfTheChurch: true,
    roleName: 'Staff',
  },
];
