// Users data with complete information based on User entity structure
export const usersData = [
  // Admin user
  {
    firstName: 'Admin',
    middleName: 'Sistema',
    paternalLastName: 'ConfeJAS',
    maternalLastName: 'System',
    dni: '00000001',
    birthDate: new Date('1990-01-01'),
    gender: 'Male',
    phone: '999000001',
    email: 'admin@confejas.com',
    address: 'Av. Administración 100',
    department: 'Lima',
    medicalCondition: null,
    keyCode: 'ADMIN001',
    stakeName: 'Los Olivos',
    ward: 'Administración',
    age: '34',
    isMemberOfTheChurch: true,
    notes: 'Usuario administrador del sistema',
    roleName: 'Admin',
    companyName: null,
  },

  // Staff users (5)
  {
    firstName: 'Carlos',
    middleName: 'Alberto',
    paternalLastName: 'Rodriguez',
    maternalLastName: 'Martinez',
    dni: '45678912',
    birthDate: new Date('1995-03-15'),
    gender: 'Male',
    phone: '987654321',
    email: 'carlos.rodriguez@confejas.com',
    address: 'Av. Principal 123',
    department: 'Lima',
    medicalCondition: null,
    keyCode: 'STAFF001',
    stakeName: 'Los Olivos',
    ward: 'San Juan',
    age: '29',
    isMemberOfTheChurch: true,
    notes: 'Coordinador de logística',
    roleName: 'Staff',
    companyName: 'Compañía Alfa',
  },
  {
    firstName: 'Ana',
    middleName: 'Maria',
    paternalLastName: 'Garcia',
    maternalLastName: 'Lopez',
    dni: '12345678',
    birthDate: new Date('1992-07-22'),
    gender: 'Female',
    phone: '912345678',
    email: 'ana.garcia@confejas.com',
    address: 'Jr. Los Olivos 456',
    department: 'Lima',
    medicalCondition: 'Diabetes tipo 2',
    keyCode: 'STAFF002',
    stakeName: 'Barranca',
    ward: 'Santa Rosa',
    age: '32',
    isMemberOfTheChurch: true,
    notes: 'Coordinadora de actividades',
    roleName: 'Staff',
    companyName: 'Compañía Beta',
  },
  {
    firstName: 'Miguel',
    middleName: 'Angel',
    paternalLastName: 'Torres',
    maternalLastName: 'Ruiz',
    dni: '34567891',
    birthDate: new Date('1993-09-25'),
    gender: 'Male',
    phone: '944556677',
    email: 'miguel.torres@confejas.com',
    address: 'Psje. La Esperanza 654',
    department: 'Lima',
    medicalCondition: null,
    keyCode: 'STAFF003',
    stakeName: 'Las Palmeras',
    ward: 'El Retablo',
    age: '31',
    isMemberOfTheChurch: true,
    notes: 'Encargado de seguridad',
    roleName: 'Staff',
    companyName: 'Compañía Gamma',
  },
  {
    firstName: 'Patricia',
    middleName: 'Elena',
    paternalLastName: 'Vargas',
    maternalLastName: 'Castillo',
    dni: '56789123',
    birthDate: new Date('1998-05-18'),
    gender: 'Female',
    phone: '955443322',
    email: 'patricia.vargas@confejas.com',
    address: 'Calle Counseling 321',
    department: 'Lima',
    medicalCondition: null,
    keyCode: 'STAFF004',
    stakeName: 'Huaral',
    ward: 'Tahuantinsuyo',
    age: '26',
    isMemberOfTheChurch: true,
    notes: 'Coordinadora de talleres',
    roleName: 'Staff',
    companyName: 'Compañía Delta',
  },
  {
    firstName: 'Roberto',
    middleName: 'Luis',
    paternalLastName: 'Mendoza',
    maternalLastName: 'Silva',
    dni: '87654321',
    birthDate: new Date('1990-12-10'),
    gender: 'Male',
    phone: '998877665',
    email: 'roberto.mendoza@confejas.com',
    address: 'Av. Tecnología 789',
    department: 'Lima',
    medicalCondition: null,
    keyCode: 'STAFF005',
    stakeName: 'Los Olivos',
    ward: 'Pro',
    age: '34',
    isMemberOfTheChurch: true,
    notes: 'Soporte técnico',
    roleName: 'Staff',
    companyName: null,
  },

  // Participants (20)
  {
    firstName: 'Sofia',
    middleName: 'Isabella',
    paternalLastName: 'Ramirez',
    maternalLastName: 'Flores',
    dni: '78912345',
    birthDate: new Date('2001-04-12'),
    gender: 'Female',
    phone: '933221100',
    email: 'sofia.ramirez@email.com',
    address: 'Urb. Los Pinos 987',
    department: 'Lima',
    medicalCondition: null,
    keyCode: null,
    stakeName: 'Los Olivos',
    ward: 'Las Palmeras',
    age: '23',
    isMemberOfTheChurch: true,
    notes: 'Taller de música',
    roleName: 'Participant',
    companyName: 'Compañía Alfa',
  },
  {
    firstName: 'Diego',
    middleName: 'Alejandro',
    paternalLastName: 'Morales',
    maternalLastName: 'Herrera',
    dni: '23456789',
    birthDate: new Date('2000-11-08'),
    gender: 'Male',
    phone: '922334455',
    email: 'diego.morales@email.com',
    address: 'Av. Juventud 147',
    department: 'Lima',
    medicalCondition: 'Asma leve',
    keyCode: null,
    stakeName: 'Barranca',
    ward: 'Santa Luzmila',
    age: '24',
    isMemberOfTheChurch: true,
    notes: 'Taller de deportes',
    roleName: 'Participant',
    companyName: 'Compañía Beta',
  },
  {
    firstName: 'Valentina',
    middleName: 'Nicole',
    paternalLastName: 'Castro',
    maternalLastName: 'Valdez',
    dni: '91234567',
    birthDate: new Date('1998-08-30'),
    gender: 'Female',
    phone: '911223344',
    email: 'valentina.castro@email.com',
    address: 'Jr. Las Flores 258',
    department: 'Lima',
    medicalCondition: null,
    keyCode: null,
    stakeName: 'Las Palmeras',
    ward: 'La Libertad',
    age: '26',
    isMemberOfTheChurch: false,
    notes: 'Taller de arte',
    roleName: 'Participant',
    companyName: 'Compañía Alfa',
  },
  {
    firstName: 'Sebastian',
    middleName: 'Eduardo',
    paternalLastName: 'Jimenez',
    maternalLastName: 'Peña',
    dni: '67891234',
    birthDate: new Date('1999-02-14'),
    gender: 'Male',
    phone: '955667788',
    email: 'sebastian.jimenez@email.com',
    address: 'Calle San Martin 369',
    department: 'Lima',
    medicalCondition: null,
    keyCode: null,
    stakeName: 'Huaral',
    ward: 'Ermitaño',
    age: '25',
    isMemberOfTheChurch: true,
    notes: 'Taller de fotografía',
    roleName: 'Participant',
    companyName: 'Compañía Gamma',
  },
  {
    firstName: 'Camila',
    middleName: 'Andrea',
    paternalLastName: 'Ramos',
    maternalLastName: 'Gonzalez',
    dni: '45612378',
    birthDate: new Date('2002-06-03'),
    gender: 'Female',
    phone: '944558899',
    email: 'camila.ramos@email.com',
    address: 'Av. Los Heroes 741',
    department: 'Lima',
    medicalCondition: 'Alergia a mariscos',
    keyCode: null,
    stakeName: 'Los Olivos',
    ward: 'Mercurio',
    age: '22',
    isMemberOfTheChurch: true,
    notes: 'Taller de cocina',
    roleName: 'Participant',
    companyName: 'Compañía Delta',
  },
  {
    firstName: 'Mateo',
    middleName: 'Ignacio',
    paternalLastName: 'Sandoval',
    maternalLastName: 'Medina',
    dni: '32178945',
    birthDate: new Date('2001-12-21'),
    gender: 'Male',
    phone: '933445566',
    email: 'mateo.sandoval@email.com',
    address: 'Psje. El Dorado 852',
    department: 'Lima',
    medicalCondition: null,
    keyCode: null,
    stakeName: 'Barranca',
    ward: 'Condevilla',
    age: '23',
    isMemberOfTheChurch: true,
    notes: 'Taller de teatro',
    roleName: 'Participant',
    companyName: 'Compañía Alfa',
  },
  {
    firstName: 'Isabella',
    middleName: 'Fernanda',
    paternalLastName: 'Delgado',
    maternalLastName: 'Rojas',
    dni: '78945612',
    birthDate: new Date('2000-01-17'),
    gender: 'Female',
    phone: '922773355',
    email: 'isabella.delgado@email.com',
    address: 'Urb. Santa Rosa 963',
    department: 'Lima',
    medicalCondition: null,
    keyCode: null,
    stakeName: 'Las Palmeras',
    ward: 'Año Nuevo',
    age: '24',
    isMemberOfTheChurch: true,
    notes: 'Taller de danza',
    roleName: 'Participant',
    companyName: 'Compañía Beta',
  },
  {
    firstName: 'Nicolas',
    middleName: 'Emilio',
    paternalLastName: 'Vega',
    maternalLastName: 'Paredes',
    dni: '15948726',
    birthDate: new Date('1997-09-05'),
    gender: 'Male',
    phone: '911884477',
    email: 'nicolas.vega@email.com',
    address: 'Jr. La Libertad 159',
    department: 'Lima',
    medicalCondition: 'Hipertensión',
    keyCode: null,
    stakeName: 'Huaral',
    ward: 'Tupac Amaru',
    age: '27',
    isMemberOfTheChurch: false,
    notes: 'Taller de programación',
    roleName: 'Participant',
    companyName: 'Compañía Gamma',
  },
  {
    firstName: 'Lucia',
    middleName: 'Gabriela',
    paternalLastName: 'Fernandez',
    maternalLastName: 'Soto',
    dni: '65432198',
    birthDate: new Date('2003-03-28'),
    gender: 'Female',
    phone: '966778899',
    email: 'lucia.fernandez@email.com',
    address: 'Av. Las Américas 456',
    department: 'Lima',
    medicalCondition: null,
    keyCode: null,
    stakeName: 'Los Olivos',
    ward: 'Sol de Oro',
    age: '21',
    isMemberOfTheChurch: true,
    notes: 'Taller de manualidades',
    roleName: 'Participant',
    companyName: 'Compañía Delta',
  },
  {
    firstName: 'Joaquin',
    middleName: 'Andres',
    paternalLastName: 'Navarro',
    maternalLastName: 'Cruz',
    dni: '88776655',
    birthDate: new Date('1999-07-19'),
    gender: 'Male',
    phone: '955667744',
    email: 'joaquin.navarro@email.com',
    address: 'Calle Los Jardines 789',
    department: 'Lima',
    medicalCondition: null,
    keyCode: null,
    stakeName: 'Barranca',
    ward: 'Perú',
    age: '25',
    isMemberOfTheChurch: true,
    notes: 'Taller de liderazgo',
    roleName: 'Participant',
    companyName: 'Compañía Delta',
  },
  {
    firstName: 'Martina',
    middleName: 'Valentina',
    paternalLastName: 'Quispe',
    maternalLastName: 'Huaman',
    dni: '99887766',
    birthDate: new Date('2002-10-11'),
    gender: 'Female',
    phone: '933556677',
    email: 'martina.quispe@email.com',
    address: 'Jr. Progreso 321',
    department: 'Lima',
    medicalCondition: 'Alergia al polen',
    keyCode: null,
    stakeName: 'Las Palmeras',
    ward: 'Carabayllo',
    age: '22',
    isMemberOfTheChurch: true,
    notes: 'Taller de escritura creativa',
    roleName: 'Participant',
    companyName: 'Compañía Alfa',
  },
  {
    firstName: 'Benjamin',
    middleName: 'Santiago',
    paternalLastName: 'Ortiz',
    maternalLastName: 'Campos',
    dni: '11223344',
    birthDate: new Date('2001-05-06'),
    gender: 'Male',
    phone: '944667788',
    email: 'benjamin.ortiz@email.com',
    address: 'Av. Industrial 654',
    department: 'Lima',
    medicalCondition: null,
    keyCode: null,
    stakeName: 'Huaral',
    ward: 'Huaral',
    age: '23',
    isMemberOfTheChurch: true,
    notes: 'Taller de robótica',
    roleName: 'Participant',
    companyName: 'Compañía Gamma',
  },
  {
    firstName: 'Emilia',
    middleName: 'Sofia',
    paternalLastName: 'Romero',
    maternalLastName: 'Diaz',
    dni: '55443322',
    birthDate: new Date('2000-12-15'),
    gender: 'Female',
    phone: '922334411',
    email: 'emilia.romero@email.com',
    address: 'Urb. Los Sauces 147',
    department: 'Lima',
    medicalCondition: null,
    keyCode: null,
    stakeName: 'Los Olivos',
    ward: 'Laura Caller',
    age: '24',
    isMemberOfTheChurch: false,
    notes: 'Taller de diseño gráfico',
    roleName: 'Participant',
    companyName: 'Compañía Beta',
  },
  {
    firstName: 'Lucas',
    middleName: 'Daniel',
    paternalLastName: 'Aguilar',
    maternalLastName: 'Vera',
    dni: '66554433',
    birthDate: new Date('1998-04-22'),
    gender: 'Male',
    phone: '911445566',
    email: 'lucas.aguilar@email.com',
    address: 'Calle Esperanza 258',
    department: 'Lima',
    medicalCondition: null,
    keyCode: null,
    stakeName: 'Barranca',
    ward: 'Zarumilla',
    age: '26',
    isMemberOfTheChurch: true,
    notes: 'Taller de emprendimiento',
    roleName: 'Participant',
    companyName: 'Compañía Delta',
  },
  {
    firstName: 'Renata',
    middleName: 'Alejandra',
    paternalLastName: 'Benitez',
    maternalLastName: 'Ponce',
    dni: '77665544',
    birthDate: new Date('2003-09-30'),
    gender: 'Female',
    phone: '966557788',
    email: 'renata.benitez@email.com',
    address: 'Jr. Los Alamos 369',
    department: 'Lima',
    medicalCondition: 'Astigmatismo',
    keyCode: null,
    stakeName: 'Las Palmeras',
    ward: 'Santa Rosa de Lima',
    age: '21',
    isMemberOfTheChurch: true,
    notes: 'Taller de oratoria',
    roleName: 'Participant',
    companyName: 'Compañía Alfa',
  },
  {
    firstName: 'Gabriel',
    middleName: 'Matias',
    paternalLastName: 'Cordova',
    maternalLastName: 'Rios',
    dni: '88997766',
    birthDate: new Date('1999-11-12'),
    gender: 'Male',
    phone: '955443377',
    email: 'gabriel.cordova@email.com',
    address: 'Av. Los Pinos 741',
    department: 'Lima',
    medicalCondition: null,
    keyCode: null,
    stakeName: 'Huaral',
    ward: 'El Ermitaño Alto',
    age: '25',
    isMemberOfTheChurch: true,
    notes: 'Taller de ajedrez',
    roleName: 'Participant',
    companyName: 'Compañía Gamma',
  },
  {
    firstName: 'Antonella',
    middleName: 'Micaela',
    paternalLastName: 'Salazar',
    maternalLastName: 'Pacheco',
    dni: '99886655',
    birthDate: new Date('2002-02-25'),
    gender: 'Female',
    phone: '933778899',
    email: 'antonella.salazar@email.com',
    address: 'Psje. La Paz 852',
    department: 'Lima',
    medicalCondition: null,
    keyCode: null,
    stakeName: 'Los Olivos',
    ward: 'Naranjal',
    age: '22',
    isMemberOfTheChurch: true,
    notes: 'Taller de yoga',
    roleName: 'Participant',
    companyName: 'Compañía Beta',
  },
  {
    firstName: 'Leonardo',
    middleName: 'Felipe',
    paternalLastName: 'Espinoza',
    maternalLastName: 'Guerrero',
    dni: '11998877',
    birthDate: new Date('2001-08-07'),
    gender: 'Male',
    phone: '944889900',
    email: 'leonardo.espinoza@email.com',
    address: 'Urb. El Trebol 963',
    department: 'Lima',
    medicalCondition: 'Intolerancia a la lactosa',
    keyCode: null,
    stakeName: 'Barranca',
    ward: 'Fiori',
    age: '23',
    isMemberOfTheChurch: false,
    notes: 'Taller de carpintería',
    roleName: 'Participant',
    companyName: 'Compañía Beta',
  },
  {
    firstName: 'Valeria',
    middleName: 'Catalina',
    paternalLastName: 'Molina',
    maternalLastName: 'Caceres',
    dni: '22334455',
    birthDate: new Date('2000-06-18'),
    gender: 'Female',
    phone: '922667788',
    email: 'valeria.molina@email.com',
    address: 'Calle Victoria 159',
    department: 'Lima',
    medicalCondition: null,
    keyCode: null,
    stakeName: 'Las Palmeras',
    ward: 'Collique',
    age: '24',
    isMemberOfTheChurch: true,
    notes: 'Taller de canto',
    roleName: 'Participant',
    companyName: 'Compañía Alfa',
  },
  {
    firstName: 'Thiago',
    middleName: 'Alexander',
    paternalLastName: 'Santillan',
    maternalLastName: 'Bravo',
    dni: '33445566',
    birthDate: new Date('1997-01-29'),
    gender: 'Male',
    phone: '911556677',
    email: 'thiago.santillan@email.com',
    address: 'Jr. San Pedro 753',
    department: 'Lima',
    medicalCondition: null,
    keyCode: null,
    stakeName: 'Huaral',
    ward: 'Unificada',
    age: '27',
    isMemberOfTheChurch: true,
    notes: 'Taller de guitarra',
    roleName: 'Participant',
    companyName: 'Compañía Gamma',
  },
];
