interface RoomData {
  roomNumber: string;
  buildingName: string;
  floorNumber: number;
  roomTypeName: string;
  totalBeds: number;
  isWeddingRoom?: boolean;
}

// Rooms data with specific room numbers and configurations
export const roomsData: RoomData[] = [
  // Building 1 rooms
  // Floor 1
  {
    roomNumber: 'C101',
    buildingName: 'Edificio',
    floorNumber: 1,
    roomTypeName: 'Edificio',
    totalBeds: 10,
  },
  {
    roomNumber: 'C102',
    buildingName: 'Edificio',
    floorNumber: 1,
    roomTypeName: 'Edificio',
    totalBeds: 8,
  },
  {
    roomNumber: 'C103',
    buildingName: 'Edificio',
    floorNumber: 1,
    roomTypeName: 'Edificio',
    totalBeds: 8,
  },
  {
    roomNumber: 'C104',
    buildingName: 'Edificio',
    floorNumber: 1,
    roomTypeName: 'Edificio',
    totalBeds: 10,
  },
  {
    roomNumber: 'C105',
    buildingName: 'Edificio',
    floorNumber: 1,
    roomTypeName: 'Edificio',
    totalBeds: 8,
  },
  {
    roomNumber: 'C106',
    buildingName: 'Edificio',
    floorNumber: 1,
    roomTypeName: 'Edificio',
    totalBeds: 10,
  },
  {
    roomNumber: 'C107',
    buildingName: 'Edificio',
    floorNumber: 1,
    roomTypeName: 'Edificio',
    totalBeds: 8,
  },
  {
    roomNumber: 'C108',
    buildingName: 'Edificio',
    floorNumber: 1,
    roomTypeName: 'Edificio',
    totalBeds: 2,
    isWeddingRoom: true,
  },
  {
    roomNumber: 'C109',
    buildingName: 'Edificio',
    floorNumber: 1,
    roomTypeName: 'Edificio',
    totalBeds: 10,
  },
  {
    roomNumber: 'C110',
    buildingName: 'Edificio',
    floorNumber: 1,
    roomTypeName: 'Edificio',
    totalBeds: 8,
  },
  {
    roomNumber: 'C111',
    buildingName: 'Edificio',
    floorNumber: 1,
    roomTypeName: 'Edificio',
    totalBeds: 10,
  },
  {
    roomNumber: 'C112',
    buildingName: 'Edificio',
    floorNumber: 1,
    roomTypeName: 'Edificio',
    totalBeds: 8,
  },
  {
    roomNumber: 'C113',
    buildingName: 'Edificio',
    floorNumber: 1,
    roomTypeName: 'Edificio',
    totalBeds: 8,
  },
  {
    roomNumber: 'C114',
    buildingName: 'Edificio',
    floorNumber: 1,
    roomTypeName: 'Edificio',
    totalBeds: 10,
  },

  // Floor 2
  {
    roomNumber: 'C201',
    buildingName: 'Edificio',
    floorNumber: 2,
    roomTypeName: 'Edificio',
    totalBeds: 10,
  },
  {
    roomNumber: 'C202',
    buildingName: 'Edificio',
    floorNumber: 2,
    roomTypeName: 'Edificio',
    totalBeds: 8,
  },
  {
    roomNumber: 'C203',
    buildingName: 'Edificio',
    floorNumber: 2,
    roomTypeName: 'Edificio',
    totalBeds: 8,
  },
  {
    roomNumber: 'C204',
    buildingName: 'Edificio',
    floorNumber: 2,
    roomTypeName: 'Edificio',
    totalBeds: 10,
  },
  {
    roomNumber: 'C205',
    buildingName: 'Edificio',
    floorNumber: 2,
    roomTypeName: 'Edificio',
    totalBeds: 8,
  },
  {
    roomNumber: 'C206',
    buildingName: 'Edificio',
    floorNumber: 2,
    roomTypeName: 'Edificio',
    totalBeds: 10,
  },
  {
    roomNumber: 'C207',
    buildingName: 'Edificio',
    floorNumber: 2,
    roomTypeName: 'Edificio',
    totalBeds: 8,
  },
  {
    roomNumber: 'C208',
    buildingName: 'Edificio',
    floorNumber: 2,
    roomTypeName: 'Edificio',
    totalBeds: 2,
    isWeddingRoom: true,
  },
  {
    roomNumber: 'C209',
    buildingName: 'Edificio',
    floorNumber: 2,
    roomTypeName: 'Edificio',
    totalBeds: 5,
  },
  {
    roomNumber: 'C210',
    buildingName: 'Edificio',
    floorNumber: 2,
    roomTypeName: 'Edificio',
    totalBeds: 8,
  },
  {
    roomNumber: 'C211',
    buildingName: 'Edificio',
    floorNumber: 2,
    roomTypeName: 'Edificio',
    totalBeds: 5,
  },
  {
    roomNumber: 'C212',
    buildingName: 'Edificio',
    floorNumber: 2,
    roomTypeName: 'Edificio',
    totalBeds: 8,
  },
  {
    roomNumber: 'C213',
    buildingName: 'Edificio',
    floorNumber: 2,
    roomTypeName: 'Edificio',
    totalBeds: 8,
  },
  {
    roomNumber: 'C214',
    buildingName: 'Edificio',
    floorNumber: 2,
    roomTypeName: 'Edificio',
    totalBeds: 5,
  },

  // Floor 3
  {
    roomNumber: 'C301',
    buildingName: 'Edificio',
    floorNumber: 3,
    roomTypeName: 'Edificio',
    totalBeds: 5,
  },
  {
    roomNumber: 'C302',
    buildingName: 'Edificio',
    floorNumber: 3,
    roomTypeName: 'Edificio',
    totalBeds: 4,
  },
  {
    roomNumber: 'C303',
    buildingName: 'Edificio',
    floorNumber: 3,
    roomTypeName: 'Edificio',
    totalBeds: 8,
  },
  {
    roomNumber: 'C304',
    buildingName: 'Edificio',
    floorNumber: 3,
    roomTypeName: 'Edificio',
    totalBeds: 5,
  },
  {
    roomNumber: 'C305',
    buildingName: 'Edificio',
    floorNumber: 3,
    roomTypeName: 'Edificio',
    totalBeds: 4,
  },
  {
    roomNumber: 'C306',
    buildingName: 'Edificio',
    floorNumber: 3,
    roomTypeName: 'Edificio',
    totalBeds: 5,
  },
  {
    roomNumber: 'C307',
    buildingName: 'Edificio',
    floorNumber: 3,
    roomTypeName: 'Edificio',
    totalBeds: 4,
  },
  {
    roomNumber: 'C308',
    buildingName: 'Edificio',
    floorNumber: 3,
    roomTypeName: 'Edificio',
    totalBeds: 2,
    isWeddingRoom: true,
  },
  {
    roomNumber: 'C309',
    buildingName: 'Edificio',
    floorNumber: 3,
    roomTypeName: 'Edificio',
    totalBeds: 5,
  },
  {
    roomNumber: 'C310',
    buildingName: 'Edificio',
    floorNumber: 3,
    roomTypeName: 'Edificio',
    totalBeds: 4,
  },
  {
    roomNumber: 'C311',
    buildingName: 'Edificio',
    floorNumber: 3,
    roomTypeName: 'Edificio',
    totalBeds: 5,
  },
  {
    roomNumber: 'C312',
    buildingName: 'Edificio',
    floorNumber: 3,
    roomTypeName: 'Edificio',
    totalBeds: 4,
  },
  {
    roomNumber: 'C313',
    buildingName: 'Edificio',
    floorNumber: 3,
    roomTypeName: 'Edificio',
    totalBeds: 4,
  },
  {
    roomNumber: 'C314',
    buildingName: 'Edificio',
    floorNumber: 3,
    roomTypeName: 'Edificio',
    totalBeds: 5,
  },

  // Building 2 rooms
  {
    roomNumber: 'B4',
    buildingName: 'Bungalow',
    floorNumber: 1,
    roomTypeName: 'Bungalow',
    totalBeds: 9,
  },
  {
    roomNumber: 'B5',
    buildingName: 'Bungalow',
    floorNumber: 1,
    roomTypeName: 'Bungalow',
    totalBeds: 12,
  },
  {
    roomNumber: 'B6',
    buildingName: 'Bungalow',
    floorNumber: 1,
    roomTypeName: 'Bungalow',
    totalBeds: 12,
  },
  {
    roomNumber: 'B7',
    buildingName: 'Bungalow',
    floorNumber: 1,
    roomTypeName: 'Bungalow',
    totalBeds: 14,
  },
  {
    roomNumber: 'B8',
    buildingName: 'Bungalow',
    floorNumber: 1,
    roomTypeName: 'Bungalow',
    totalBeds: 14,
  },
  {
    roomNumber: 'B9',
    buildingName: 'Bungalow',
    floorNumber: 1,
    roomTypeName: 'Bungalow',
    totalBeds: 13,
  },
  {
    roomNumber: 'B10',
    buildingName: 'Bungalow',
    floorNumber: 1,
    roomTypeName: 'Bungalow',
    totalBeds: 13,
  },
  {
    roomNumber: 'B11',
    buildingName: 'Bungalow',
    floorNumber: 1,
    roomTypeName: 'Bungalow',
    totalBeds: 14,
  },
  {
    roomNumber: 'B12',
    buildingName: 'Bungalow',
    floorNumber: 1,
    roomTypeName: 'Bungalow',
    totalBeds: 12,
  },
  {
    roomNumber: 'B13',
    buildingName: 'Bungalow',
    floorNumber: 1,
    roomTypeName: 'Bungalow',
    totalBeds: 12,
  },
  {
    roomNumber: 'B14',
    buildingName: 'Bungalow',
    floorNumber: 1,
    roomTypeName: 'Bungalow',
    totalBeds: 12,
  },
  {
    roomNumber: 'B15',
    buildingName: 'Bungalow',
    floorNumber: 1,
    roomTypeName: 'Bungalow',
    totalBeds: 9,
  },
  {
    roomNumber: 'B16',
    buildingName: 'Bungalow',
    floorNumber: 1,
    roomTypeName: 'Bungalow',
    totalBeds: 9,
  },
  {
    roomNumber: 'B17',
    buildingName: 'Bungalow',
    floorNumber: 1,
    roomTypeName: 'Bungalow',
    totalBeds: 12,
  },
  {
    roomNumber: 'B18',
    buildingName: 'Bungalow',
    floorNumber: 1,
    roomTypeName: 'Bungalow',
    totalBeds: 12,
  },
];
