// Rooms data with specific room numbers and configurations
export const roomsData = [
  // Building 1 rooms
  {
    roomNumber: '101',
    buildingName: 'Albergues',
    floorNumber: 1,
    roomTypeName: 'Albergue',
    totalBeds: 10,
  },
  {
    roomNumber: '102',
    buildingName: 'Albergues',
    floorNumber: 1,
    roomTypeName: 'Albergue',
    totalBeds: 10,
  },
  {
    roomNumber: '103',
    buildingName: 'Albergues',
    floorNumber: 1,
    roomTypeName: 'Albergue',
    totalBeds: 10,
  },
  {
    roomNumber: '104',
    buildingName: 'Albergues',
    floorNumber: 1,
    roomTypeName: 'Albergue',
    totalBeds: 10,
  },
  {
    roomNumber: '105',
    buildingName: 'Albergues',
    floorNumber: 1,
    roomTypeName: 'Albergue',
    totalBeds: 10,
  },
  {
    roomNumber: '106',
    buildingName: 'Albergues',
    floorNumber: 1,
    roomTypeName: 'Albergue',
    totalBeds: 10,
  },
  {
    roomNumber: '107',
    buildingName: 'Albergues',
    floorNumber: 1,
    roomTypeName: 'Albergue',
    totalBeds: 10,
  },
  {
    roomNumber: '108',
    buildingName: 'Albergues',
    floorNumber: 1,
    roomTypeName: 'Albergue',
    totalBeds: 10,
  },
  {
    roomNumber: '201',
    buildingName: 'Albergues',
    floorNumber: 2,
    roomTypeName: 'Albergue',
    totalBeds: 10,
  },
  {
    roomNumber: '202',
    buildingName: 'Albergues',
    floorNumber: 2,
    roomTypeName: 'Albergue',
    totalBeds: 10,
  },
  {
    roomNumber: '203',
    buildingName: 'Albergues',
    floorNumber: 2,
    roomTypeName: 'Albergue',
    totalBeds: 10,
  },
  {
    roomNumber: '204',
    buildingName: 'Albergues',
    floorNumber: 2,
    roomTypeName: 'Albergue',
    totalBeds: 10,
  },
  {
    roomNumber: '205',
    buildingName: 'Albergues',
    floorNumber: 2,
    roomTypeName: 'Albergue',
    totalBeds: 10,
  },
  {
    roomNumber: '206',
    buildingName: 'Albergues',
    floorNumber: 2,
    roomTypeName: 'Albergue',
    totalBeds: 10,
  },
  {
    roomNumber: '207',
    buildingName: 'Albergues',
    floorNumber: 2,
    roomTypeName: 'Albergue',
    totalBeds: 10,
  },
  {
    roomNumber: '208',
    buildingName: 'Albergues',
    floorNumber: 2,
    roomTypeName: 'Albergue',
    totalBeds: 10,
  },
  {
    roomNumber: '301',
    buildingName: 'Albergues',
    floorNumber: 3,
    roomTypeName: 'Albergue',
    totalBeds: 10,
  },
  {
    roomNumber: '302',
    buildingName: 'Albergues',
    floorNumber: 3,
    roomTypeName: 'Albergue',
    totalBeds: 10,
  },
  {
    roomNumber: '303',
    buildingName: 'Albergues',
    floorNumber: 3,
    roomTypeName: 'Albergue',
    totalBeds: 10,
  },
  {
    roomNumber: '304',
    buildingName: 'Albergues',
    floorNumber: 3,
    roomTypeName: 'Albergue',
    totalBeds: 10,
  },
  {
    roomNumber: '305',
    buildingName: 'Albergues',
    floorNumber: 3,
    roomTypeName: 'Albergue',
    totalBeds: 10,
  },
  {
    roomNumber: '306',
    buildingName: 'Albergues',
    floorNumber: 3,
    roomTypeName: 'Albergue',
    totalBeds: 10,
  },
  {
    roomNumber: '307',
    buildingName: 'Albergues',
    floorNumber: 3,
    roomTypeName: 'Albergue',
    totalBeds: 10,
  },
  {
    roomNumber: '308',
    buildingName: 'Albergues',
    floorNumber: 3,
    roomTypeName: 'Albergue',
    totalBeds: 10,
  },

  // Building 2 rooms
  {
    roomNumber: 'AUDITORIO',
    buildingName: 'Auditorio',
    floorNumber: 1,
    roomTypeName: 'Auditorio',
    totalBeds: 134,
  },

  // Building 3 rooms
  {
    roomNumber: 'CAPILLA',
    buildingName: 'Capilla',
    floorNumber: 1,
    roomTypeName: 'Capilla',
    totalBeds: 52,
  },

  // Building 4 rooms
  {
    roomNumber: 'B1',
    buildingName: 'Bungalows',
    floorNumber: 1,
    roomTypeName: 'Bungalow',
    totalBeds: 12,
  },
  {
    roomNumber: 'B2',
    buildingName: 'Bungalows',
    floorNumber: 1,
    roomTypeName: 'Bungalow',
    totalBeds: 12,
  },
  {
    roomNumber: 'B3',
    buildingName: 'Bungalows',
    floorNumber: 1,
    roomTypeName: 'Bungalow',
    totalBeds: 12,
  },
  {
    roomNumber: 'B4',
    buildingName: 'Bungalows',
    floorNumber: 1,
    roomTypeName: 'Bungalow',
    totalBeds: 12,
  },
  {
    roomNumber: 'B5',
    buildingName: 'Bungalows',
    floorNumber: 1,
    roomTypeName: 'Bungalow',
    totalBeds: 12,
  },
  {
    roomNumber: 'B6',
    buildingName: 'Bungalows',
    floorNumber: 1,
    roomTypeName: 'Bungalow',
    totalBeds: 12,
  },
  {
    roomNumber: 'B7',
    buildingName: 'Bungalows',
    floorNumber: 2,
    roomTypeName: 'Bungalow',
    totalBeds: 12,
  },
  {
    roomNumber: 'B8',
    buildingName: 'Bungalows',
    floorNumber: 2,
    roomTypeName: 'Bungalow',
    totalBeds: 12,
  },
  {
    roomNumber: 'B9',
    buildingName: 'Bungalows',
    floorNumber: 2,
    roomTypeName: 'Bungalow',
    totalBeds: 12,
  },
  {
    roomNumber: 'B10',
    buildingName: 'Bungalows',
    floorNumber: 2,
    roomTypeName: 'Bungalow',
    totalBeds: 12,
  },
  {
    roomNumber: 'B11',
    buildingName: 'Bungalows',
    floorNumber: 2,
    roomTypeName: 'Bungalow',
    totalBeds: 12,
  },
  {
    roomNumber: 'B12',
    buildingName: 'Bungalows',
    floorNumber: 2,
    roomTypeName: 'Bungalow',
    totalBeds: 12,
  },
  {
    roomNumber: 'B13',
    buildingName: 'Bungalows',
    floorNumber: 3,
    roomTypeName: 'Bungalow',
    totalBeds: 12,
  },
  {
    roomNumber: 'B14',
    buildingName: 'Bungalows',
    floorNumber: 3,
    roomTypeName: 'Bungalow',
    totalBeds: 12,
  },
  {
    roomNumber: 'B15',
    buildingName: 'Bungalows',
    floorNumber: 3,
    roomTypeName: 'Bungalow',
    totalBeds: 12,
  },
  {
    roomNumber: 'B16',
    buildingName: 'Bungalows',
    floorNumber: 3,
    roomTypeName: 'Bungalow',
    totalBeds: 12,
  },
];
